version: '3.8'
services:
  pgrouting:
    image: pgrouting/pgrouting:12-3.0-3.0.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
    #  - ./data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d